// Source/features-ui/src/components/featureNumberInput/index.tsx
// @ts-nocheck
import { FunctionalComponent, h } from "preact";
import { Feature, FeatureValueType } from '../../models';
import { Text, TextField, PrimaryButton, DefaultButton } from '@fluentui/react';
import { useState } from "preact/hooks";

type Props = {
    feature: Feature,
    value: number,
    handleFeatureChange: (feature: Feature, newValue: FeatureValueType) => void
};

const FeatureNumberInput: FunctionalComponent<Props> = (props) => {
    const {
        feature,
        value,
        handleFeatureChange
    } = props;

    const [newValue, setNewValue] = useState(value);

    const {
        readonly,
        uiPrefix,
        uiSuffix
    } = feature;

    const isNumeric = !isNaN(newValue);
    const hasChanged = value !== newValue;

    const canSave = hasChanged;
    const canCancel = hasChanged;

    const saveDisabled = !isNumeric;

    const onTextChanged = (e: React.KeyboardEvent<HTMLInputElement | HTMLTextAreaElement>) => {
        const target = e.target as HTMLInputElement;
        setNewValue(parseFloat(target.value));
    }

    const onValidateButtonClicked = () => {
        handleFeatureChange(feature, newValue);
    }

    const onCancelButtonClicked = () => {
        setNewValue(value);
    }

    return (
        <div>
            <p>
                <Text block variant="large">
                    {feature.name}
                </Text>
                {feature.description &&
                    <Text block variant="small">
                        {feature.description}
                    </Text>
                }
            </p>
            <TextField
                value={newValue.toString()}
                disabled={readonly}
                onKeyUp={onTextChanged}
                prefix={uiPrefix || undefined}
                suffix={uiSuffix || undefined}
            />
            <p>
                {canSave && (
                    <PrimaryButton
                        text="Save"
                        onClick={() => onValidateButtonClicked()}
                        disabled={saveDisabled}
                        allowDisabledFocus
                    />
                )}
                {canCancel && (
                    <DefaultButton
                        text="Cancel"
                        onClick={() => onCancelButtonClicked()}
                        allowDisabledFocus
                        style={{ marginLeft: 12 }}
                    />
                )}
            </p>
        </div>
    );
};

export default FeatureNumberInput;

// Source/features-ui/src/components/FeatureNumberInput.svelte
<script lang="ts">
	import { updateFeatureValue } from '$functions/api';
	import type { Feature } from '$models';
	import { dashboardStore } from '$stores/dashboard';
	import { Button, TextBlock, NumberBox } from 'fluent-svelte';

	const { selectedAuthScheme } = dashboardStore;

	export let feature: Feature;
	export let value: number;

	let newValue = value;

	$: hasChanged = value !== newValue;

	$: canSave = hasChanged;
	$: canCancel = hasChanged;

	const onValidateButtonClicked = () => {
		updateFeatureValue($selectedAuthScheme, feature.name, newValue);
	};

	const onCancelButtonClicked = () => {
		newValue = value;
	};
</script>

<div>
	<p style="display: flex; flex-direction: column;">
		<TextBlock variant="subtitle">
			{feature.name}
		</TextBlock>
		{#if feature.description}
			<TextBlock variant="caption">
				{feature.description}
			</TextBlock>
		{/if}
	</p>

	<NumberBox
		bind:value={newValue}
		disabled={feature.readonly}
		prefix={feature.uiPrefix}
		suffix={feature.uiSuffix}
	/>

	<p>
		{#if canSave}
			<Button variant="accent" on:click={onValidateButtonClicked}>Save</Button>
		{/if}
		{#if canCancel}
			<Button on:click={onCancelButtonClicked}>Cancel</Button>
		{/if}
	</p>
</div>
