// Source/features-ui/src/components/featureCombobox/index.tsx
// @ts-nocheck
import { FunctionalComponent, h } from "preact";
import { Feature, FeatureValueType, FeatureChoicesType } from '../../models';
import { Text, Dropdown, PrimaryButton, DefaultButton, IDropdownOption } from '@fluentui/react';
import { useState } from "preact/hooks";

type Props = {
    feature: Feature,
    value: FeatureChoicesType,
    choices: FeatureValueType[],
    handleFeatureChange: (feature: Feature, newValue: FeatureValueType) => void
};

const FeatureCombobox: FunctionalComponent<Props> = (props) => {
    const {
        feature,
        value,
        choices,
        handleFeatureChange
    } = props;

    const {
        readonly,
        uiPrefix,
        uiSuffix
    } = feature;

    const [newValue, setNewValue] = useState(value);

    const hasChanged = value !== newValue;

    const canSave = hasChanged;
    const canCancel = hasChanged;

    const onChange = (event: React.FormEvent<HTMLDivElement>, item: IDropdownOption): void => {
        setNewValue(item.key);
    };

    const onValidateButtonClicked = () => {
        handleFeatureChange(feature, newValue);
    }

    const onCancelButtonClicked = () => {
        setNewValue(value);
    }

    const options: IDropdownOption[] = choices
        .map(c => {
            return {
                key: c,
                text: typeof c === 'string' ? c : c.toString()
            } as IDropdownOption;
        });

    return (
        <div>
            <p>
                <Text block variant="large">
                    {feature.name}
                </Text>
                {feature.description &&
                    <Text block variant="small">
                        {feature.description}
                    </Text>
                }
            </p>
            <Dropdown
                placeholder="Select an option"
                defaultSelectedKey={newValue}
                options={options}
                disabled={readonly}
                onChange={onChange}
                prefix={uiPrefix || undefined}
                suffix={uiSuffix || undefined}
            />
            <p>
                {canSave && (
                    <PrimaryButton
                        text="Save"
                        onClick={() => onValidateButtonClicked()}
                        allowDisabledFocus
                    />
                )}
                {canCancel && (
                    <DefaultButton
                        text="Cancel"
                        onClick={() => onCancelButtonClicked()}
                        allowDisabledFocus
                        style={{ marginLeft: 12 }}
                    />
                )}
            </p>
        </div>
    );
};

export default FeatureCombobox;

// Source/features-ui/src/components/FeatureCombobox.svelte
<script lang="ts">
	import { updateFeatureValue } from '$functions/api';
	import type { Feature, FeatureChoicesType } from '$models';
	import { dashboardStore } from '$stores/dashboard';
	import { Button, TextBlock, ComboBox } from 'fluent-svelte';

	const { selectedAuthScheme } = dashboardStore;

	export let feature: Feature;
	export let value: FeatureChoicesType;

	const items = feature.choices.map((choice) => ({ name: choice }));

	let newValue = value;

	$: hasChanged = value !== newValue;

	$: canSave = hasChanged;
	$: canCancel = hasChanged;

	const onValidateButtonClicked = () => {
		updateFeatureValue($selectedAuthScheme, feature.name, newValue);
	};

	const onCancelButtonClicked = () => {
		newValue = value;
	};
</script>

<div>
	<p style="display: flex; flex-direction: column;">
		<TextBlock variant="subtitle">
			{feature.name}
		</TextBlock>
		{#if feature.description}
			<TextBlock variant="caption">
				{feature.description}
			</TextBlock>
		{/if}
	</p>

	<ComboBox
		bind:value={newValue}
		{items}
		placeholder="Select an option"
		disabled={feature.readonly}
		prefix={feature.uiPrefix}
		suffix={feature.uiSuffix}
	/>

	<p>
		{#if canSave}
			<Button variant="accent" on:click={onValidateButtonClicked}>Save</Button>
		{/if}
		{#if canCancel}
			<Button on:click={onCancelButtonClicked}>Cancel</Button>
		{/if}
	</p>
</div>
